### ISSUE TITLE
Is it possible to support displaying battery power?

### ISSUE THREAD

**Issue by 1100100** [imbushuo/mac-precision-touchpad#431] opened 2021-08-28 08:24 UTC
Is it possible to support displaying battery power?

[AB#755](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/755)

**Comment by lloydo3000** [comment] 2021-08-28 08:26
Duplicate of #413

**Closed** 2021-10-02 10:41 UTC
Labels: enhancement
