### ISSUE TITLE
Add Three finger drag function ? 

### ISSUE THREAD

**Issue by nulllpoint** [imbushuo/mac-precision-touchpad#419] opened 2021-07-14 14:09 UTC
If can add three finger drag function, it's very very very perfect !!! 
Of course, the current version is perfect !!!
It revived my Magic Trackpad2 on my windows

[AB#731](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/731)

**Comment by imbushuo** [comment] 2021-07-15 06:54
Duplicate of https://github.com/imbushuo/mac-precision-touchpad/issues/415

**Closed by imbushuo** 2021-07-15 06:54 UTC
Labels: enhancement

**Comment by JOJOradioDA** [comment] 2022-11-15 12:18
这个功能还没开发吧，我看关闭了以为做完了呢。7月15号关闭，9月3号都还有人发帖求这个功能来着。
