### ISSUE TITLE
Mouse keeps disappearing

### ISSUE THREAD

**Issue by bhermann17** [imbushuo/mac-precision-touchpad#226] opened 2019-10-01 20:51 UTC
Upon attempting to wake up my laptop after putting it to sleep, the mouse often disappears. I'm not sure if others have experienced this, but it's quite frustrating as the only way to fix it is to restart my computer entirely. And even then, it doesn't always fix it.

Hardware: 2017 MacBook Pro
Software: Latest Update for Windows 10 Bootcamp

**Comment by mul14** [comment] 2019-10-02 08:42
Duplicate: https://github.com/imbushuo/mac-precision-touchpad/issues/203

**Comment by imbushuo** [comment] 2019-10-02 21:35
Duplicate of #203 

By the way, it is not necessary to reboot the computer. Restart the device in device manager helps.

**Closed by imbushuo** 2019-10-02 21:35 UTC
