### ISSUE TITLE
Cannot click in games

### ISSUE THREAD

**Issue by Jershwar** [imbushuo/mac-precision-touchpad#320] opened 2020-07-07 21:54 UTC
**Pre-report checks**

- [x] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

Yes, the most similar entry I could find is on this Github is here: https://github.com/imbushuo/mac-precision-touchpad/issues/292

**Describe the bug**

I cannot use LMB/RMB on my trackpad in games (specifically tested in GTA San Andreas). Strangely enough, the trackpad works when you plug in a USB mouse (even if you unplug it immediately), but as soon as you restart the game the issue persists. It does not occur/works normally with the default driver or Trackpad++.

**To Reproduce**

Simply open GTA: San Andreas or a similar game. You won't be able to click on the menu items. 

**Expected behavior**

To be able to interact (LMB, RMB, mouse movement) as normal. 

**Traces**

N/A

**Environment**

MacBook Pro 13" Early 2015 running the latest Windows 10 Pro on bootcamp with a virtually clean install.

Many thanks for your help and apologies if I've been unclear about anything.

**Comment by imbushuo** [comment] 2020-07-11 06:44
Duplicate of https://github.com/imbushuo/mac-precision-touchpad/issues/206

**Closed by imbushuo** 2020-07-11 06:44 UTC
Labels: bug
