### ISSUE TITLE
CAN NOT USE IN GAME!!!

### ISSUE THREAD

**Issue by a200411044** [imbushuo/mac-precision-touchpad#246] opened 2019-12-10 02:41 UTC
no respond on league of legends
pls help....

**Comment by a200411044** [comment] 2019-12-10 02:42
the cursor can still move but cannot use left/right click or other function....

**Comment by carrottopadc** [comment] 2019-12-10 02:44
When I used the drivers on my 15 inch, I had a similar problem. It appeared as though it would only do one action at a time when it was in full screen. Ie move, click, key press etc

**Comment by a200411044** [comment] 2019-12-10 03:19
i have tried in windows mode and it didnt work too

**Comment by imbushuo** [comment] 2019-12-13 08:21
Duplicate of https://github.com/imbushuo/mac-precision-touchpad/issues/206, I am currently aware of that. Discussion will be tracked there.

**Closed by imbushuo** 2019-12-13 08:21 UTC
