### ISSUE TITLE
bluetooth connectivity

### ISSUE THREAD

**Issue by miranemec** [imbushuo/mac-precision-touchpad#299] opened 2020-05-11 11:28 UTC
I saw some request for BT in past, but there is no one in present. Is there any chance to get BT version? May I help you somehow? This driver is great, just BT is missing for me.

**Comment by baltedewit** [comment] 2020-05-19 07:59
Duplicate of https://github.com/imbushuo/mac-precision-touchpad/issues/229 ?

**Comment by evanbebop** [comment] 2020-05-21 05:37
I downloaded the latest version 3805 amd64 version. This problem also occurred on my mbp 15' late 2016. I uninstalled the original Apple trackpad from the device manager first and then installed the 3805 version. The trackpad on my mac works fine and magic pad also works fine through usb connection. However, it cannot be detected sometime through BT, and even if it is connected to windows, it just works like the original trackpad. The computer recognizes it as a mouse and all the function you have created do not work on this magic pad. Strangely, the trackpad on the mac works all fine(having all the function you create).

**Comment by 1Revenger1** [comment] 2020-05-23 05:57
@evanbebop this driver doesn't have any bluetooth support yet

**Comment by evanbebop** [comment] 2020-05-23 07:13
Thank you very much. I just misunderstood the way to use this drive. Waiting for the further function. Will buy a coffee tomorrow.

Best wishes,

Zhuoran

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Avery Black <notifications@github.com>
发送时间: Saturday, May 23, 2020 1:57:56 PM
收件人: imbushuo/mac-precision-touchpad <mac-precision-touchpad@noreply.github.com>
抄送: evanbebop <voyager_no6@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [imbushuo/mac-precision-touchpad] bluetooth connectivity (#299)


@evanbebop<https://github.com/evanbebop> this driver doesn't have any bluetooth support yet

―

**Comment by nrudnyk** [comment] 2020-06-01 19:19
is there any plans to implement BT functionality?

**Comment by karthi6662003** [comment] 2020-06-03 19:38
I am using MacBook air 2017 .Built in trackpad works excellent but wireless Apple magic trackpad 2 works only when connected via USB .If I connect  via Bluetooth it detects as a mouse .
any progress on Bluetooth functionality .

**Comment by AhmadChaiban** [comment] 2020-06-05 00:14
Duplicate of #229

**Comment by iomect** [comment] 2020-06-08 04:47
Thank you very much for your contribution.
Just send 3 coffees for you~
Wait for MagicTrackpad 2 bluetooth support.

**Closed** 2021-06-01 09:06 UTC
Labels: enhancement
