### ISSUE TITLE
Request: Support for Magic Trackpad 1 (Not Magic Trackpad 2)

### ISSUE THREAD

**Issue by samirotiv** [imbushuo/mac-precision-touchpad#446] opened 2021-10-26 16:18 UTC
Hi,

Appreciate the work you've done for the community, thanks for the project. I could see that the Magic Trackpad 1 was explicitly missing from the list of supported devices.

Posting here to request support for this, if it is possible. Let me know if I can help in any way!

Best,
Samir.

[AB#774](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/774)

**Comment by oriolpetit** [comment] 2021-10-30 09:44
Duplicate of [Request to work with Magic Trackpad 1#358](https://github.com/imbushuo/mac-precision-touchpad/issues/358l)

**Closed** 2021-11-12 05:53 UTC

**Comment by tnaseem** [comment] 2021-11-18 01:06
Just a heads up. There's a typo in the link. Duplicate is actually:
https://github.com/imbushuo/mac-precision-touchpad/issues/358
