### ISSUE TITLE
Trackpad gaming errors.

### ISSUE THREAD

**Issue by jsteweii** [imbushuo/mac-precision-touchpad#280] opened 2020-03-21 23:43 UTC
I'm on a Macbook pro 15 inch from 2017. I'm running Windows 10 all updated. I tried your driver, because the bootcamp driver wouldn't allow me to move and shoot at the same time in-game. This happens in various older games. 

Your driver (Build 3805) did solve that problem in some of the newer of the older games I tried. But unfortunately the oldest of the games, either crashes to desktop, with an error pointing to a mouse problem, or simply freezes the cursor in-game, as in it can't be moved. 

The game it freezes in, is Medal of Honor 2010 and the game it crashes is Army Men.

I don't know what other details to give you. Please advise.

Best regards,

-johnny

**Comment by imbushuo** [comment] 2020-03-24 10:47
Duplicate of #206 (so I am going to close this one, please track that issue.) In fact, there was a time I implemented legacy mouse fallback but later I removed it. I will evaluating adding it back in the future.

**Closed by imbushuo** 2020-03-24 10:47 UTC
Labels: bug
