### ISSUE TITLE
[Air 2015 Early] I set bottom right corner register as right click. But sadly it fails 50% of times and doing left click instead. Too much irritating while using chrome!!! I confirm this bug by trying reinstalling different versions. My bottom right corner works perfect in Apple driver. Plssss fix it

### ISSUE THREAD

**Issue by dendimonster** [imbushuo/mac-precision-touchpad#271] opened 2020-03-03 05:32 UTC
**Pre-report checks**

- [ ] Have you checked (use search) [Azure DevOps Board](https://ligstd.visualstudio.com/Apple%20PTP%20Trackpad/_workitems/recentlyupdated) and Github issues for known bugs and plans?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Traces**
If applicable, add WPP traces to help explain your problem.

**Environment**
Add your device model, driver type (USB or SPI) and OS version here.

**Comment by imbushuo** [comment] 2020-03-03 21:13
Duplicate of #256

**Closed by imbushuo** 2020-03-03 21:13 UTC
Labels: bug
