### ISSUE TITLE
SPI Build 3561 "device not found" error on Macbook 11,5

### ISSUE THREAD

**Issue by markreg** [imbushuo/mac-precision-touchpad#225] opened 2019-09-22 20:19 UTC
I'm unable to get the SPI Build 3561 driver working on a recent build of Win10. The touchpad disappears if I try to update the UMDF driver and says device not found before I rollback.

Currently using the USB UMDF driver, however it seems to have some significant issues with scroll sensitivity and lag.

**Comment by imbushuo** [comment] 2019-09-24 08:20
Need clarification on the driver you use, since USB and SPI use different implementation. UMDF driver has higher latency by design - this won't get mitigated until these drivers get merged in near future.

**Comment by markreg** [comment] 2019-09-24 17:26
Currently using AmtPtpDeviceUsbUm, x64 and I attempted to install AmtPtpDeviceSpiKm, x64.

First tried via "Have Disk" prompt from "Apple Precision Touchpad Device (User-mode)" in Device Manager, the install is successful but later it shows "device not found" code 10 and the cursor disappears.

**Comment by imbushuo** [comment] 2019-09-24 17:28
@markreg This is unsupported scenario. Until further notice, you should stay on AmtPtpDeviceUsbUm and never attempt to install AmtPtpDeviceSpiKm.

**Comment by imbushuo** [comment] 2019-09-24 17:28
But could you please provide the device ID?

**Closed by imbushuo** 2019-09-24 17:28 UTC
Labels: bug, incomplete-report

**Comment by markreg** [comment] 2019-09-24 17:39
Vendor ID: 05AC
Product ID: 0274
REV: 0624
MI: 02

**Comment by markreg** [comment] 2019-09-24 17:41
The primary issue seems to come when I _begin_ scrolling in either direction, there is a long delay and the cursor moves, rather than scrolls in most cases. Then the scroll motion is similar to what I experience on macOS.
